name: swe_est
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - numpy>=1.13.0
  - pandas
  - matplotlib
  - seaborn
  - scipy
  - folium
  - scikit-learn
  - rasterio
  - cartopy
  - pytest
  - sphinx
  - captum 
  
  - pip:
      - -r requirements.txt
